"""empty message

Revision ID: 021cf33f4a1b
Revises: 25b69aaf91c4
Create Date: 2022-01-22 17:57:54.424135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '021cf33f4a1b'
down_revision = '25b69aaf91c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('milege', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('description', sa.Text(), nullable=True))
    op.drop_constraint('event_title_key', 'event', type_='unique')
    op.drop_constraint('vehicle_title_key', 'vehicle', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('vehicle_title_key', 'vehicle', ['title'])
    op.create_unique_constraint('event_title_key', 'event', ['title'])
    op.drop_column('event', 'description')
    op.drop_column('event', 'milege')
    # ### end Alembic commands ###
