"""empty message

Revision ID: 32648bb2ced6
Revises: 2bc776e51132
Create Date: 2022-01-14 19:35:34.515355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32648bb2ced6'
down_revision = '2bc776e51132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('vehicle_avatar', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle', 'vehicle_avatar')
    # ### end Alembic commands ###
