"""changed type of data in table Vehicle

Revision ID: a2faa8ae0e00
Revises: 7b87b618d9b2
Create Date: 2022-01-07 00:16:43.142522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2faa8ae0e00'
down_revision = '7b87b618d9b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicle', 'engine_type',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('vehicle', 'transmission_type',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('vehicle', 'body',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicle', 'body',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('vehicle', 'transmission_type',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('vehicle', 'engine_type',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
