"""empty message

Revision ID: b09c1e9a981f
Revises: 8d34a875740c
Create Date: 2021-12-28 13:39:12.170939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b09c1e9a981f'
down_revision = '8d34a875740c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('event_vehicle_id_fkey', 'event', type_='foreignkey')
    op.create_foreign_key(None, 'event', 'vehicle', ['vehicle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.create_foreign_key('event_vehicle_id_fkey', 'event', 'user', ['vehicle_id'], ['id'])
    # ### end Alembic commands ###
